animal = input("What is your favorite animal? \n ")
print("--------------------")
why = input("Why is it your favorite? \n ")
print("--------------------")
sound = input("What sound does it make? \n ")
print("--------------------")
habitat = input("Where does it live? \n ")
print("--------------------")
color = input("What color is it? \n")
print("--------------------")
time = input("How long have you liked it? \n ")
print("--------------------")
food = input("What does it eat? \n ")
print("--------------------")
social = input("What does it live with? \n ")
print("--------------------") 
companions = input("Whats a group of it called? \n ")
print("--------------------")
experience = input("Where have you seen it? \n ")
print("--------------------")
print(" So your favorite animal is a " + animal + ". Because it's " + why + " and it makes " + sound + ". It also lives in " + habitat + ". It is " + color + ". You have liked it for your " + time + ". It eats " + food + " and it lives with " + social + ". A group of it is called " + companions + ". You have seen it at " + experience) 